version: "3"
services:
  pipeline-example-{version}:
    environment:
    - MQTT_HOST=192.168.22.26
    - MQTT_PORT=1883
    ports:
    - "8067:8080"
    container_name: pipeline-example-{version}
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/pipeline-example:{version}
