version: "3"
services:
  pipeline-example-{version}:
    environment:
    - MQTT_HOST=192.168.22.26
    - MQTT_PORT=1883
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    build:
      context: .
      dockerfile: ../Dockerfile
    image: 192.168.233.1:5000/pipeline-example:{version}
    networks:
      dev:
        aliases:
         - pipeline-example-{version}
networks:
  dev:
    external:
      name: dev
